export const SET_SESSIONS = 'SET_SESSIONS';
export const ADD_SESSION = 'ADD_SESSION';
export const DUPLICATE_SESSION = 'DUPLICATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';
export const SET_LOADING = 'SET_LOADING';